### PR TITLE
Cancelable AsyncTask

### PR DESCRIPTION
**Pull request by theGnartist**
This allows for the developer to cancel a TextCrawler's task.  This allows for better usage inside of a list view as well as preventing Activity lifecycle related crashes.

### CODE REVIEW

**Comment by LeonardoCardoso** [comment]
Thanks, @theGnartist.

**Comment by chiragw15** [comment]
Thanks @theGnartist . Desperately needed cancel method. There was a memory leak due to this. @LeonardoCardoso when will the latest version be released?

**Comment by LeonardoCardoso** [comment]
@chiragw15 I’m afraid I don’t have time to support it anymore. But could you or @theGnartist create a new `aar` as a new version and upload it to https://github.com/LeonardoCardoso/mvn-repo?

**Comment by ink1804** [comment]
1.2.2 version still hasnt cancel() method...

**Comment by LeonardoCardoso** [comment]
@ink1804 please see my previous answer.

**Comment by LeonardoCardoso** [comment]
@ink1804  @chiragw15  Done. Check the version 2.0.0.

**Pull request merged**
